version: '3.3'
services :
  db:
    image: postgres
    ports:
      - "6348:6348"
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: todos-app
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - "8080:8080"